// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOAGwvKw4PGEBbw5fJtKdPxfGRk4SC-RI',
    appId: '1:633442745672:web:81c0ef46c2495eeefec77d',
    messagingSenderId: '633442745672',
    projectId: 'expense-tracker-ff784',
    authDomain: 'expense-tracker-ff784.firebaseapp.com',
    storageBucket: 'expense-tracker-ff784.firebasestorage.app',
    measurementId: 'G-5FT4GH2KED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkrW04YbD7eFNlad6djmz15rtw8hsTaw0',
    appId: '1:633442745672:android:fd48f5bbf984bef7fec77d',
    messagingSenderId: '633442745672',
    projectId: 'expense-tracker-ff784',
    storageBucket: 'expense-tracker-ff784.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPRUIOpmyrKoTJZSgHszURyYFmjpPyV-U',
    appId: '1:633442745672:ios:1814fcc53c59ba50fec77d',
    messagingSenderId: '633442745672',
    projectId: 'expense-tracker-ff784',
    storageBucket: 'expense-tracker-ff784.firebasestorage.app',
    androidClientId: '633442745672-ndr9e3m3iu1qnsgu8712ptr6t9t22hh1.apps.googleusercontent.com',
    iosClientId: '633442745672-lk5akip5b75eq65762mvvk5iv1v7cojv.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPRUIOpmyrKoTJZSgHszURyYFmjpPyV-U',
    appId: '1:633442745672:ios:1814fcc53c59ba50fec77d',
    messagingSenderId: '633442745672',
    projectId: 'expense-tracker-ff784',
    storageBucket: 'expense-tracker-ff784.firebasestorage.app',
    androidClientId: '633442745672-ndr9e3m3iu1qnsgu8712ptr6t9t22hh1.apps.googleusercontent.com',
    iosClientId: '633442745672-lk5akip5b75eq65762mvvk5iv1v7cojv.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOAGwvKw4PGEBbw5fJtKdPxfGRk4SC-RI',
    appId: '1:633442745672:web:a25f9a5c99109018fec77d',
    messagingSenderId: '633442745672',
    projectId: 'expense-tracker-ff784',
    authDomain: 'expense-tracker-ff784.firebaseapp.com',
    storageBucket: 'expense-tracker-ff784.firebasestorage.app',
    measurementId: 'G-5YQJYXRBST',
  );
}
